name: CI/CD Pipeline

on:
  push:
    branches: [main]

permissions:
  contents: read    # Allows reading repo contents
  id-token: write   # Needed if using OIDC (e.g., with Azure or AWS)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest

      - name: Build artifact
        run: |
          zip -r release.zip .
        env:
          AZURE_FUNCTIONAPP_PACKAGE_PATH: './release.zip'

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: 'Deploy to Azure Functions'
        uses: Azure/functions-action@v1
        id: deploy-to-function
        with:
          app-name: 'ghub-entra-group-automation'
          slot-name: 'Production'
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_8D6B442EE3694CBB86E9B90968B7A34C }}
